apiVersion: configuration.konghq.com/v1beta1
kind: UDPIngress
metadata:
  name: freeswitch-sip-udp
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - port: 5060
      backend:
        serviceName: freeswitch-service
        servicePort: 5060
