env:
  database: "off"

proxy:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # We will attach the Elastic IPs provisioned in Terraform here
    # service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-xxx,eipalloc-yyy"
  stream:
    # Route SIP UDP traffic to FreeSWITCH
    - containerPort: 5060
      servicePort: 5060
      protocol: UDP
      parameters: []

ingressController:
  enabled: true
  installCRDs: false
