apiVersion: v1
kind: Service
metadata:
  name: event-publisher-service
  namespace: default
  labels:
    app: event-publisher
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: esl-socket
    port: 8084
    targetPort: 8084
  selector:
    app: event-publisher
  type: ClusterIP
