output "region" {
  description = "AWS region"
  value       = var.aws_region
}

output "bastion_public_ip" {
  description = "The public IP of the Bastion jump host"
  value       = aws_instance.bastion.public_ip
}

output "proxy_public_ip" {
  description = "The static IP for Twilio to send SIP/RTP traffic to and to access pgAdmin/APIs"
  value       = aws_eip.proxy_eip.public_ip
}

output "freeswitch_private_ip" {
  description = "The private IP of the FreeSWITCH stack instance"
  value       = aws_instance.freeswitch.private_ip
}

output "ssh_bastion_tunnel_cmd" {
  description = "SSH proxy jump command to connect to the private FreeSWITCH instance"
  value       = "ssh -i ./freeswitch-key.pem -J ubuntu@${aws_instance.bastion.public_ip} ubuntu@${aws_instance.freeswitch.private_ip}"
}

# ── Generate environment variables file for shell scripts ─────────────────────

resource "local_file" "env_sh" {
  filename = "${path.module}/env.sh"
  content  = <<-EOT
    # Dynamic Environment Variables generated by Terraform
    export BASTION_IP="${aws_instance.bastion.public_ip}"
    export PROXY_IP="${aws_eip.proxy_eip.public_ip}"
    export PRIVATE_IP="${aws_instance.freeswitch.private_ip}"
    export AWS_REGION="${var.aws_region}"
    
    # Resolve absolute path to the SSH private key
    INFRA_DIR="$(cd "$(dirname "$${BASH_SOURCE[0]}")" && pwd)"
    export KEY_PATH="$INFRA_DIR/freeswitch-key.pem"
  EOT
}

resource "local_file" "hosts_k8s_yaml" {
  filename = "${path.module}/hosts_k8s.yaml"
  content  = <<-EOT
    all:
      hosts:
        node1:
          ansible_host: ${aws_instance.freeswitch.private_ip}
          ip: ${aws_instance.freeswitch.private_ip}
          access_ip: ${aws_instance.freeswitch.private_ip}
          ansible_user: ubuntu
      children:
        kube_control_plane:
          hosts:
            node1:
        kube_node:
          hosts:
            node1:
        etcd:
          hosts:
            node1:
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
        calico_rr:
          hosts: {}
      vars:
        ansible_ssh_common_args: '-o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/rajan/Projects/Telephony/infra/freeswitch-key.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@${aws_instance.bastion.public_ip}"'
  EOT
}
