apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - port: 5050
    targetPort: 80
    nodePort: 30050
  selector:
    app: pgadmin
