apiVersion: v1
kind: Service
metadata:
  name: freeswitch-service
  namespace: default
  labels:
    app: freeswitch
spec:
  ports:
  - name: sip-udp
    port: 5060
    protocol: UDP
    targetPort: 5060
  - name: sip-tcp
    port: 5060
    protocol: TCP
    targetPort: 5060
  - name: esl
    port: 8021
    protocol: TCP
    targetPort: 8021
  selector:
    app: freeswitch
  type: ClusterIP
