apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch
  namespace: {{ .Release.Namespace }}
  labels:
    app: freeswitch
spec:
  replicas: {{ .Values.freeswitch.replicaCount }}
  selector:
    matchLabels:
      app: freeswitch
  template:
    metadata:
      labels:
        app: freeswitch
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: freeswitch
        image: "{{ .Values.global.registry }}/{{ .Values.freeswitch.image.repository }}:{{ .Values.freeswitch.image.tag }}"
        imagePullPolicy: {{ .Values.freeswitch.image.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_NICE
            - SYS_RAWIO
        resources:
          {{- toYaml .Values.freeswitch.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/freeswitch/freeswitch.xml
          subPath: freeswitch.xml
      volumes:
      - name: config-volume
        configMap:
          name: freeswitch-config
