apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  pgadmin-email: {{ .Values.pgadmin.email | b64enc | quote }}
  pgadmin-password: {{ .Values.pgadmin.password | b64enc | quote }}
